// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseFile(arg1) {
  return window['go']['main']['App']['ChooseFile'](arg1);
}

export function Msgalert(arg1) {
  return window['go']['main']['App']['Msgalert'](arg1);
}

export function Send(arg1) {
  return window['go']['main']['App']['Send'](arg1);
}

export function SendDo(arg1, arg2) {
  return window['go']['main']['App']['SendDo'](arg1, arg2);
}
