// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseFile(arg1:{[key: string]: {[key: string]: any}}):Promise<{[key: string]: {[key: string]: any}}>;

export function Msgalert(arg1:string):Promise<void>;

export function Send(arg1:{[key: string]: {[key: string]: any}}):Promise<string>;

export function SendDo(arg1:string,arg2:string):Promise<void>;
