// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Listen() {
  return window['go']['main']['App']['Listen']();
}

export function Msgalert(arg1) {
  return window['go']['main']['App']['Msgalert'](arg1);
}
