// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseReceivePath() {
  return window['go']['main']['App']['ChooseReceivePath']();
}

export function Listen(arg1, arg2, arg3) {
  return window['go']['main']['App']['Listen'](arg1, arg2, arg3);
}

export function Msgalert(arg1) {
  return window['go']['main']['App']['Msgalert'](arg1);
}
