// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseReceivePath():Promise<string>;

export function Listen(arg1:number,arg2:string,arg3:string):Promise<string>;

export function Msgalert(arg1:string):Promise<void>;
